name: PR Preview

on:
  workflow_dispatch:
    inputs:
      PR_REPO:
        required: true
        type: choice
        options: ['pingcap/docs', 'pingcap/docs-cn']
        default: 'pingcap/docs'
        description: 'The repository to preview'
      PR_NUMBER:
        required: true
        type: number
        description: 'The PR number to preview'
      PREVIEW_PRODUCT:
        required: true
        type: choice
        options: ["tidb", "tidbcloud"]
        default: "tidb"
        description: 'The product to preview'
      PREVIEW_BRANCH:
        required: true
        type: string
        default: 'master'
        description: 'The branch to preview, such as master, release-x.y'

jobs:
  copy_files:
    runs-on: ubuntu-latest

    steps:
    - name: Check out destination repository
      uses: actions/checkout@v3
      with:
        path: pingcap-docs-website-scaffold

    - name: Check out source repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.PR_REPO }}
        path: source-repo

    - name: Copy files
      run: |
        chmod +x pingcap-docs-website-scaffold/sync_pr.sh

        if [ "${{ github.event.inputs.PR_REPO }}" = "pingcap/docs" ]
        then
          export LANG="en"
        elif [ "${{ github.event.inputs.PR_REPO }}" = "pingcap/docs-cn" ]
        then
          export LANG="zh"
        fi

        pingcap-docs-website-scaffold/sync_pr.sh ${{ github.event.inputs.PR_NUMBER }} source-repo pingcap-docs-website-scaffold/markdown-pages/$LANG/${{ github.event.inputs.PREVIEW_PRODUCT }}/${{ github.event.inputs.PREVIEW_BRANCH }}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        cd source-repo
        LAST_COMMIT=$(git rev-parse HEAD)
        cd ../pingcap-docs-website-scaffold
        git status
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Update files from https://github.com/${{ github.event.inputs.PR_REPO }}/pull/${{ github.event.inputs.PR_NUMBER }}/commits/$LAST_COMMIT" || echo "No changes to commit"
        git push
